/** Catalogue Phase 1 → 1.1 — actions, obligations, matières (niveaux 1–20). */
export type AssetKind = 'stock' | 'bond' | 'commodity';

export type CatalogAsset = {
  symbol: string;
  name: string;
  sector: string;
  kind: AssetKind;
  price0: number;
  mu: number;
  sigma: number;
  anchor: number;
  kappa: number;
  unlockLevel: number;
  blurb: string;
};

export const ASSET_CATALOG: CatalogAsset[] = [
  // —— Niv. 1 : blue chips ——
  {
    symbol: 'TECH',
    name: 'TechNova SA',
    sector: 'tech',
    kind: 'stock',
    price0: 120,
    mu: 0.00012,
    sigma: 0.018,
    anchor: 125,
    kappa: 0.06,
    unlockLevel: 1,
    blurb: 'Logiciels cloud et IA d’entreprise.',
  },
  {
    symbol: 'RETL',
    name: 'RetailMax SE',
    sector: 'consumer',
    kind: 'stock',
    price0: 85,
    mu: 0.00008,
    sigma: 0.014,
    anchor: 88,
    kappa: 0.07,
    unlockLevel: 1,
    blurb: 'Grande distribution omnicanale.',
  },
  {
    symbol: 'ENRG',
    name: 'Energia Corp',
    sector: 'energy',
    kind: 'stock',
    price0: 64,
    mu: 0.00005,
    sigma: 0.022,
    anchor: 70,
    kappa: 0.05,
    unlockLevel: 1,
    blurb: 'Énergie mixte, pétrole et renouvelable.',
  },
  {
    symbol: 'HLTH',
    name: 'MediLife AG',
    sector: 'health',
    kind: 'stock',
    price0: 95,
    mu: 0.0001,
    sigma: 0.012,
    anchor: 98,
    kappa: 0.08,
    unlockLevel: 1,
    blurb: 'Pharma et dispositifs médicaux.',
  },
  {
    symbol: 'BANK',
    name: 'SolidBank Group',
    sector: 'finance',
    kind: 'stock',
    price0: 48,
    mu: 0.00006,
    sigma: 0.016,
    anchor: 50,
    kappa: 0.07,
    unlockLevel: 1,
    blurb: 'Banque universelle européenne.',
  },
  {
    symbol: 'CLOUD',
    name: 'CloudPeak Systems',
    sector: 'tech',
    kind: 'stock',
    price0: 142,
    mu: 0.00014,
    sigma: 0.02,
    anchor: 150,
    kappa: 0.05,
    unlockLevel: 1,
    blurb: 'Infrastructure cloud hyperscale.',
  },
  {
    symbol: 'FOOD',
    name: 'FreshBite Foods',
    sector: 'consumer',
    kind: 'stock',
    price0: 36,
    mu: 0.00007,
    sigma: 0.013,
    anchor: 38,
    kappa: 0.08,
    unlockLevel: 1,
    blurb: 'Agroalimentaire et marques premium.',
  },
  {
    symbol: 'CHIP',
    name: 'SemiCore NV',
    sector: 'tech',
    kind: 'stock',
    price0: 210,
    mu: 0.00015,
    sigma: 0.024,
    anchor: 220,
    kappa: 0.045,
    unlockLevel: 1,
    blurb: 'Semiconducteurs et puces IA.',
  },
  // —— Niv. 2–10 : diversification actions ——
  {
    symbol: 'AUTO',
    name: 'AutoDrive Motors',
    sector: 'industrial',
    kind: 'stock',
    price0: 78,
    mu: 0.00009,
    sigma: 0.019,
    anchor: 82,
    kappa: 0.06,
    unlockLevel: 2,
    blurb: 'Automobile électrique et ADAS.',
  },
  {
    symbol: 'MINE',
    name: 'OreForge Mining',
    sector: 'materials',
    kind: 'stock',
    price0: 52,
    mu: 0.00004,
    sigma: 0.026,
    anchor: 55,
    kappa: 0.04,
    unlockLevel: 3,
    blurb: 'Métaux industriels et cuivre.',
  },
  {
    symbol: 'MEDIA',
    name: 'StreamWave Media',
    sector: 'consumer',
    kind: 'stock',
    price0: 29,
    mu: 0.00011,
    sigma: 0.021,
    anchor: 32,
    kappa: 0.055,
    unlockLevel: 4,
    blurb: 'Streaming et studios numériques.',
  },
  {
    symbol: 'UTIL',
    name: 'GridPower Utilities',
    sector: 'utilities',
    kind: 'stock',
    price0: 41,
    mu: 0.00003,
    sigma: 0.01,
    anchor: 42,
    kappa: 0.09,
    unlockLevel: 5,
    blurb: 'Réseaux électriques régulés.',
  },
  {
    symbol: 'AIR',
    name: 'SkyLink Airways',
    sector: 'industrial',
    kind: 'stock',
    price0: 67,
    mu: 0.00008,
    sigma: 0.023,
    anchor: 70,
    kappa: 0.05,
    unlockLevel: 6,
    blurb: 'Compagnie aérienne long-courrier.',
  },
  {
    symbol: 'PAY',
    name: 'PayNova Fintech',
    sector: 'finance',
    kind: 'stock',
    price0: 88,
    mu: 0.00013,
    sigma: 0.02,
    anchor: 92,
    kappa: 0.055,
    unlockLevel: 7,
    blurb: 'Paiements digitaux et wallets.',
  },
  {
    symbol: 'LUXE',
    name: 'Maison Luxe',
    sector: 'consumer',
    kind: 'stock',
    price0: 310,
    mu: 0.0001,
    sigma: 0.015,
    anchor: 320,
    kappa: 0.07,
    unlockLevel: 8,
    blurb: 'Maison de luxe et maroquinerie.',
  },
  {
    symbol: 'SOFT',
    name: 'AppForge Soft',
    sector: 'tech',
    kind: 'stock',
    price0: 56,
    mu: 0.00011,
    sigma: 0.017,
    anchor: 60,
    kappa: 0.06,
    unlockLevel: 9,
    blurb: 'Éditeurs SaaS B2B.',
  },
  {
    symbol: 'INSR',
    name: 'Shield Mutual',
    sector: 'finance',
    kind: 'stock',
    price0: 73,
    mu: 0.00005,
    sigma: 0.011,
    anchor: 75,
    kappa: 0.085,
    unlockLevel: 10,
    blurb: 'Assurance dommages et vie.',
  },
  // —— Niv. 11–14 : obligations ——
  {
    symbol: 'BOND10',
    name: 'Oblig. Souveraine 10Y',
    sector: 'fixed_income',
    kind: 'bond',
    price0: 100,
    mu: 0.00002,
    sigma: 0.004,
    anchor: 100,
    kappa: 0.12,
    unlockLevel: 11,
    blurb: 'Obligation d’État fictive — faible risque, faible rendement.',
  },
  {
    symbol: 'CORP5',
    name: 'Oblig. Corporate AAA',
    sector: 'fixed_income',
    kind: 'bond',
    price0: 98,
    mu: 0.00003,
    sigma: 0.006,
    anchor: 99,
    kappa: 0.1,
    unlockLevel: 12,
    blurb: 'Dette entreprise investment-grade.',
  },
  {
    symbol: 'GREEN',
    name: 'Green Bond EU',
    sector: 'fixed_income',
    kind: 'bond',
    price0: 101,
    mu: 0.000025,
    sigma: 0.005,
    anchor: 101,
    kappa: 0.11,
    unlockLevel: 13,
    blurb: 'Obligation verte — finance la transition.',
  },
  {
    symbol: 'HYLD',
    name: 'High Yield Notes',
    sector: 'fixed_income',
    kind: 'bond',
    price0: 92,
    mu: 0.00006,
    sigma: 0.012,
    anchor: 94,
    kappa: 0.07,
    unlockLevel: 14,
    blurb: 'Obligations haut rendement — plus volatiles.',
  },
  // —— Niv. 15–18 : matières ——
  {
    symbol: 'GOLD',
    name: 'Or (once)',
    sector: 'commodities',
    kind: 'commodity',
    price0: 1850,
    mu: 0.00004,
    sigma: 0.016,
    anchor: 1900,
    kappa: 0.04,
    unlockLevel: 15,
    blurb: 'Métal précieux — valeur refuge fictive.',
  },
  {
    symbol: 'OIL',
    name: 'Pétrole Brent',
    sector: 'commodities',
    kind: 'commodity',
    price0: 78,
    mu: 0.00003,
    sigma: 0.028,
    anchor: 80,
    kappa: 0.035,
    unlockLevel: 16,
    blurb: 'Contrat pétrole — très sensible aux chocs.',
  },
  {
    symbol: 'WHEAT',
    name: 'Blé Soft Red',
    sector: 'commodities',
    kind: 'commodity',
    price0: 22,
    mu: 0.00002,
    sigma: 0.024,
    anchor: 23,
    kappa: 0.045,
    unlockLevel: 17,
    blurb: 'Céréales — saisonnalité et climat.',
  },
  {
    symbol: 'COPR',
    name: 'Cuivre Grade A',
    sector: 'commodities',
    kind: 'commodity',
    price0: 8.4,
    mu: 0.00005,
    sigma: 0.022,
    anchor: 8.8,
    kappa: 0.05,
    unlockLevel: 18,
    blurb: 'Métal industriel — proxy activité mondiale.',
  },
  // —— Niv. 19–20 : fin Phase 1.1 ——
  {
    symbol: 'IDX',
    name: 'SMC World Index',
    sector: 'index',
    kind: 'stock',
    price0: 4200,
    mu: 0.00008,
    sigma: 0.012,
    anchor: 4300,
    kappa: 0.06,
    unlockLevel: 19,
    blurb: 'Indice diversifié du marché fictif.',
  },
  {
    symbol: 'REIT',
    name: 'Urban REIT',
    sector: 'real_estate',
    kind: 'stock',
    price0: 64,
    mu: 0.00005,
    sigma: 0.014,
    anchor: 66,
    kappa: 0.07,
    unlockLevel: 20,
    blurb: 'Foncier coté — bureaux et logistique.',
  },
];

export function blurbFor(symbol: string): string {
  return ASSET_CATALOG.find((a) => a.symbol === symbol)?.blurb ?? '';
}

export function kindFor(symbol: string): AssetKind {
  return ASSET_CATALOG.find((a) => a.symbol === symbol)?.kind ?? 'stock';
}

export const KIND_LABEL: Record<AssetKind, string> = {
  stock: 'Action',
  bond: 'Obligation',
  commodity: 'Matière',
};
