/** Catalogue Phase 1 — 15 actions fictives, déblocage progressif niveaux 1–8. */
export type CatalogAsset = {
  symbol: string;
  name: string;
  sector: string;
  price0: number;
  mu: number;
  sigma: number;
  anchor: number;
  kappa: number;
  unlockLevel: number;
  blurb: string;
};

export const ASSET_CATALOG: CatalogAsset[] = [
  {
    symbol: 'TECH',
    name: 'TechNova SA',
    sector: 'tech',
    price0: 120,
    mu: 0.00012,
    sigma: 0.018,
    anchor: 125,
    kappa: 0.06,
    unlockLevel: 1,
    blurb: 'Logiciels cloud et IA d’entreprise.',
  },
  {
    symbol: 'RETL',
    name: 'RetailMax SE',
    sector: 'consumer',
    price0: 85,
    mu: 0.00008,
    sigma: 0.014,
    anchor: 88,
    kappa: 0.07,
    unlockLevel: 1,
    blurb: 'Grande distribution omnicanale.',
  },
  {
    symbol: 'ENRG',
    name: 'Energia Corp',
    sector: 'energy',
    price0: 64,
    mu: 0.00005,
    sigma: 0.022,
    anchor: 70,
    kappa: 0.05,
    unlockLevel: 1,
    blurb: 'Énergie mixte, pétrole et renouvelable.',
  },
  {
    symbol: 'HLTH',
    name: 'MediLife AG',
    sector: 'health',
    price0: 95,
    mu: 0.0001,
    sigma: 0.012,
    anchor: 98,
    kappa: 0.08,
    unlockLevel: 1,
    blurb: 'Pharma et dispositifs médicaux.',
  },
  {
    symbol: 'BANK',
    name: 'SolidBank Group',
    sector: 'finance',
    price0: 48,
    mu: 0.00006,
    sigma: 0.016,
    anchor: 50,
    kappa: 0.07,
    unlockLevel: 1,
    blurb: 'Banque universelle européenne.',
  },
  {
    symbol: 'CLOUD',
    name: 'CloudPeak Systems',
    sector: 'tech',
    price0: 142,
    mu: 0.00014,
    sigma: 0.02,
    anchor: 150,
    kappa: 0.05,
    unlockLevel: 1,
    blurb: 'Infrastructure cloud hyperscale.',
  },
  {
    symbol: 'FOOD',
    name: 'FreshBite Foods',
    sector: 'consumer',
    price0: 36,
    mu: 0.00007,
    sigma: 0.013,
    anchor: 38,
    kappa: 0.08,
    unlockLevel: 1,
    blurb: 'Agroalimentaire et marques premium.',
  },
  {
    symbol: 'CHIP',
    name: 'SemiCore NV',
    sector: 'tech',
    price0: 210,
    mu: 0.00015,
    sigma: 0.024,
    anchor: 220,
    kappa: 0.045,
    unlockLevel: 1,
    blurb: 'Semiconducteurs et puces IA.',
  },
  {
    symbol: 'AUTO',
    name: 'AutoDrive Motors',
    sector: 'industrial',
    price0: 78,
    mu: 0.00009,
    sigma: 0.019,
    anchor: 82,
    kappa: 0.06,
    unlockLevel: 2,
    blurb: 'Automobile électrique et ADAS.',
  },
  {
    symbol: 'MINE',
    name: 'OreForge Mining',
    sector: 'materials',
    price0: 52,
    mu: 0.00004,
    sigma: 0.026,
    anchor: 55,
    kappa: 0.04,
    unlockLevel: 3,
    blurb: 'Métaux industriels et cuivre.',
  },
  {
    symbol: 'MEDIA',
    name: 'StreamWave Media',
    sector: 'consumer',
    price0: 29,
    mu: 0.00011,
    sigma: 0.021,
    anchor: 32,
    kappa: 0.055,
    unlockLevel: 4,
    blurb: 'Streaming et studios numériques.',
  },
  {
    symbol: 'UTIL',
    name: 'GridPower Utilities',
    sector: 'utilities',
    price0: 41,
    mu: 0.00003,
    sigma: 0.01,
    anchor: 42,
    kappa: 0.09,
    unlockLevel: 5,
    blurb: 'Réseaux électriques régulés.',
  },
  {
    symbol: 'AIR',
    name: 'SkyLink Airways',
    sector: 'industrial',
    price0: 67,
    mu: 0.00008,
    sigma: 0.023,
    anchor: 70,
    kappa: 0.05,
    unlockLevel: 6,
    blurb: 'Compagnie aérienne long-courrier.',
  },
  {
    symbol: 'PAY',
    name: 'PayNova Fintech',
    sector: 'finance',
    price0: 88,
    mu: 0.00013,
    sigma: 0.02,
    anchor: 92,
    kappa: 0.055,
    unlockLevel: 7,
    blurb: 'Paiements digitaux et wallets.',
  },
  {
    symbol: 'LUXE',
    name: 'Maison Luxe',
    sector: 'consumer',
    price0: 310,
    mu: 0.0001,
    sigma: 0.015,
    anchor: 320,
    kappa: 0.07,
    unlockLevel: 8,
    blurb: 'Maison de luxe et maroquinerie.',
  },
];

export function blurbFor(symbol: string): string {
  return ASSET_CATALOG.find((a) => a.symbol === symbol)?.blurb ?? '';
}
